ecomproject/api/urls.py
from django.urls import path
from api.views import *

urlpatterns = [
    path('products/', ProductListView.as_view()),
    path('products/<int:pk>/', ProductDetailView.as_view()),
    path('search/', ProductSearchView.as_view(), name="productsearch"),
    path('add-to-cart/<int:pk>/', AddProductToCart.as_view()),
    path('my-cart/', MyCartView.as_view()),
    path('manage-cart-items/<int:pk>/', ManageCartProductView.as_view()),
    path('empty-cart/', EmptyCartView.as_view()),
    path('checkout/', CheckOutView.as_view()),
    path("profile/", CustomerProfileView.as_view(), name="profile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),


    # admin side
    path("admin/orders/", AdminOrderListView.as_view(), name="adminorderlist"),
    path("admin/orders/<int:pk>/",
         AdminOrderDetailView.as_view(), name="adminorderdetail"),
    path("admin/orders-<int:pk>-change/",
         AdminOrderStatusChange.as_view(), name="adminorderstatuschange"),
    path('admin/products/', ProductListView.as_view()),
    path('admin/products/<int:pk>/', ProductDetailView.as_view()),
    path('admin/products/add/', AdminAddProductView.as_view(), name="addproduct"),
]

ecomproject/ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"
urlpatterns = [
    # customer side
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact-us/', ContactView.as_view(), name="contact"),
    path('all-products/', AllProdutView.as_view(), name="all-products"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("search/", SearchView.as_view(), name="search"),
    path("add-to-cart/<int:pro_id>/", AddToCartView.as_view(), name="add-to-cart"),
    path("my-cart/", MyCartView.as_view(), name="my-cart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="empty-cart"),

    path("checkout/", CheckOutView.as_view(), name="checkout"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/", CustomerRegistrationView.as_view(), name="register"),
    path("logout/", CustomerLogoutView.as_view(), name="logout"),
    path("login/", CustomerLoginView.as_view(), name="login"),
    path("profile/", CustomerProfileView.as_view(),
         name="profile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customer-order-detail"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgotpassword"),

    # admin side
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHome.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name="adminorder"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),
    path("admin-order-<int:pk>-change/",
         AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductadd"),

    # payment
    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
]

ecomproject/ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Ecommerce API",
        default_version='v1',
        description="Speed your ecommerce",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
    path('api/', include([
        path('', include('api.urls')),
        path('', schema_view.with_ui('swagger', cache_timeout=0),
             name='schema-swagger-ui'),
    ])),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomproject/ecomapp/models.py
from email.policy import default
from random import choices
from django.contrib.auth.models import User
from django.db import models
from django.utils import tree


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products", null=True, blank=True)
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Cart: ' + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name="cartproducts")
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="cartproducts")
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return 'Cart: ' + str(self.cart.id) + 'CartProduct: ' + str(self.id)


# tuple of the tuple
ORDER_STATUS = (
    ('Order Received', 'Order Received'),
    ('Order Processing', 'Order Processing'),
    ('On the way', 'On the way'),
    ('Order Completed', 'Order Completed'),
    ('Order Cancelled', 'Order Cancelled'),
)


METHOD = (
    ('Cash On Delivery', 'Cash on Delivery'),
    ('Khalti', 'Khalti'),
    ('Esewa', 'Esewa'),
)


class Order(models.Model):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    # payment method
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash on Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return 'Order: ' + str(self.id)

ecomproject/templates/add_to_cart.html
{% extends 'main.html' %}

{% block title %}Add to Cart {% endblock %}

{% block content %}
<h3>Product added to cart sucessfully.</h3>
{% endblock %}

ecomproject/templates/allproducts.html
{% extends 'main.html' %}
{% block title %} Our Products {% endblock %}

{% block content %}
<div class="container">
    <h3>All Products</h3>
    <hr>
    {% for category in allcategories %}
    <h4>{{category.title}}</h4>
    <div class="row">
        {% for product in category.product_set.all %}
        <div class="col-md-3">
            <div class="m-4">
                <h5><a href="{% url 'ecomapp:product-detail' product.slug %}">{{product.title}}</a></h5>
                <img src="{{product.image.url}}" alt="" class="img-fluid" style="height: 2500;object-fit:cover;">
                <p class="mt-3">Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</p>
                <a href="{% url 'ecomapp:add-to-cart' product.id %}" class="btn btn-primary">Add to Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>

    {% endfor %}
    </div>
{% endblock %}

ecomproject/templates/checkout.html
{% extends 'main.html' %}

{% block title %} Checkout {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the Cart</h3>
            <a href="{% url 'ecomapp:my-cart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <th>S.N</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </thead>
                <tbody>
                    {% for cp in cart.cartproducts.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th class="text-right" colspan="4">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Place Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/contactus.html
{% extends 'main.html' %}
{% block title %}Contact Us{% endblock %}

{% block content %}
    <h2>Contact</h2>
{% endblock %}

ecomproject/templates/customerorderdetail.html
{% extends 'main.html' %}
{% load humanize %}
{% block title %}Order Detail{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3>
            <hr>
            <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Ordered On: </span> {{ord_obj.created_at}} {{ord_obj.created_at|timesince}} ago</p>
            <p><span class="font-weight-bold">Customer Information: </span>By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Information: </span> {{ord_obj.shipping_address}} {{ord_obj.email}} </p>
            <p><span class="font-weight-bold">Payment Information: </span>Using {{ ord_obj.payment_method }} ({% if ord_obj.payment_completed %}Payment Completed{% else %}Not paid{% endif %})</p>

            <table class="table">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
            
                <tbody>
                    {% for cp in ord_obj.cart.cartproducts.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank" href="{% url 'ecomapp:product-detail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quanity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                        <tr>
                            <th colspan="4" class="text-right">Total: </th>
                            <th>Rs. {{ord_obj.total|intcomma}}/-</th>
                        </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/customerprofile.html
{% extends 'main.html' %}

{% block title %} Customer Profile {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Detail Information</h3>
            <p><span class="font-weight-bold">Name: </span>{{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span>{{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span>{{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span>{{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span>{{ customer.joined_on|date:"Y-m-d" }}</p>

        </div>
        <div class="col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered On</th>
                        <th>Status</th>
                    </tr>
                </thead>

                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:customer-order-detail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>Rs. {{order.total}}</td>
                        <td>{{order.created_at|timesince}} ago</td>
                        <td>{{order.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/esewarequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Esewa payment</title>
    <style>
        /* #myform{
            display: none;
        } */
    </style>
</head>
<body>
    <h3 style="text-align: center;">You willl be redirected to the esewa website.</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
        <input value="{{order.total}}" name="tAmt" type="text">
        <input value="{{order.total}}" name="amt" type="text">
        <input value="0" name="txAmt" type="text">
        <input value="0" name="psc" type="text">
        <input value="0" name="pdc" type="text">
        <input value="EPAYTEST" name="scd" type="text">
        <input value="order_{{order.id}}" name="pid" type="text">
        <input value="http://127.0.0.1:8000/esewa-verify/" type="text" name="su">
        <input value="{{request.build_absolute_uri}}" type="text" name="fu">
        <input value="Submit" type="submit">
    </form>
    <!-- <script>
        setTimeout(() => {
            document.getElementById("myform").submit()
        }, 500);
    </script> -->
</body>
</html>

ecomproject/templates/forgotpassword.html
{% extends 'main.html' %}
{% block title %}Forgot Password {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3>Enter your email used in making customer account to get password reset link.</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/home.html
{% extends 'main.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    <h1 class="text-center">Welcome to our website</h1>
    <div class="container">
        <hr>
        <div class="row mt-3">
            {% for product in product_list %}
            <div class="col-md-3 card">
            <h4><a href="{% url 'ecomapp:product-detail' product.slug %}">{{product.title}}</a></h4>
                <img src="{{product.image.url}}" alt="" width="200px" class="img-fluid" style="height: 2500;object-fit:cover;">
                <p class="mt-3">Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</p>
                <a href="{% url 'ecomapp:add-to-cart' product.id %}" class="btn btn-primary">Add to Cart</a>
            </div>
            {% endfor %}
        </div>
       
    </div>
    <h2>Hello</h2>

    {#  pagination #}
    <nav aria-label="...">
        <ul class="pagination">
            {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{product_list.previous_page_number}}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tableindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}

            {% for i in product_list.paginator.page_range %}
            {% if i == product_list.number %}
            <li class="page-item active"><a class="page-link">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if product_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tableindex="-1" aria-disabled="true">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>




{% endblock %}

ecomproject/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'ecomapp:home' %}">Daraz</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'ecomapp:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ecomapp:all-products' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ecomapp:my-cart' %}">My Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ecomapp:contact' %}">Contact Us</a>
                    </li>
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            My Account
                        </a>
                        <ul class="dropdown-menu">
                            {% if request.user.customer %}
                            <a class="dropdown-item" href="{% url 'ecomapp:profile' %}">My Profile</a>
                            <a class="dropdown-item" href="{% url 'ecomapp:logout' %}">Logout</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'ecomapp:register' %}">Register</a>
                            <a class="dropdown-item" href="{% url 'ecomapp:login' %}">Login</a>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0" role="search" action="{% url 'ecomapp:search' %}" method="GET">
                    <input class="form-control mr-sm-2" name="keyword" type="search" placeholder="Search" aria-label="Search" required>
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    
    {% block content %}

    {% endblock %}
</body>
</html>

ecomproject/templates/my_cart.html
{% extends 'main.html' %}

{% block title %}My Cart {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div>Items in my cart</div>
            <hr>
            {% if cart is None %}
            <h4>No item added to cart.</h4>
            {% else %}
                        <table class="table">
                            <thead>
                                <th>S.N</th>
                                <th>Product</th>
                                <th>Rate</th>
                                <th>Quantity</th>
                                <th>Subtotal</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                                {% for cp in cart.cartproducts.all %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{cp.product.title}}</td>
                                    <td>{{cp.rate}}</td>
                                    <td>{{cp.quantity}}</td>
                                    <td>{{cp.subtotal}}</td>
                                    <td>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=dec" class="btn btn-warning"> - </a>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> X </a>
                                    </td>
                                </tr>
                                {% endfor %}
                        
                                <tr>
                                    <th colspan="4" class="text-center">Total</th>
                                    <th>Rs. {{cart.total}}</th>
                                    {% if cart.cartproduct_set %}
                                    <th><a href="{% url 'ecomapp:empty-cart' %}">Empty Cart</a></th>
                                    {% endif %}
                                </tr>

                                {% if cart.cartproducts %}
                                <tr>
                                    <th><a class="btn btn-info" href="{% url 'ecomapp:checkout' %}">Checkout</a></th>
                                </tr>
                                {% endif %}
                            </tbody>
                        </table>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/product_detail.html
{% extends "main.html" %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Product: {{product.title}}</h3>
    <div class="row">
        <div class="col-md-4">
            <img src="{{product.image.url}}" alt="" class="img-fluid" />
            <div class="row">
            {% for pi in product.productimage_set.all %}
                <div class="col-md-4  p-3">
                    <img src="{{pi.image.url}}" alt="{{pi.image.title}}" class="img-fluid" style="height: 100px;object-fit:contain;" />
                </div>
            {% endfor %}
            </div>
                  
        </div>
        <div class="col-md-8">
            <h4>{{product.title}} (Viewed {{product.view_count}} times)</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: <strike>{{product.marked_price}}</strike> Rs. {{product.selling_price}}</h5>
            <a href="{% url 'ecomapp:add-to-cart' product.id %}" class="btn btn-primary">Add to Cart</a>

            <hr>
            <p class="text-info">Warranty: {{product.warranty}}</p>
            <p class="text-info">Return Policy:: {{product.return_policy}}</p>
            <p>{{product.description}}</p>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/register.html
{% extends 'main.html' %}

{% block title %} Customer Registration {% endblock %}

{% block content %}
<style>
    .errorlist{
        color: red;
        text-decoration-style: none;
        list-style-type: none;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">Register as a Customer</button>
            </form>
            <p>Already have account? <a href="{% url 'ecomapp:login' %}">Login here</a></p>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/search.html
{% extends 'main.html' %}

{% block title %} Search {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            <div class="row mt-3">
                {% for product in product_list %}
                <div class="col-md-3">
                    <h4><a href="{% url 'ecomapp:product-detail' product.slug %}">{{product.title}}</a></h4>
                    <img src="{{product.image.url}}" alt="" width="200px" class="img-fluid" style="height: 2500;object-fit:cover;">
                    <p class="mt-3">Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</p>
                    <a href="{% url 'ecomapp:add-to-cart' product.id %}" class="btn btn-primary">Add to Cart</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}