ecomproject/api/urls.py
from django.urls import path
from api.views import *

urlpatterns = [
    path('products/', ProductListView.as_view()),
    path('products/<int:pk>/', ProductDetailView.as_view()),
    path('search/', ProductSearchView.as_view(), name="productsearch"),
    path('add-to-cart/<int:pk>/', AddProductToCart.as_view()),
    path('my-cart/', MyCartView.as_view()),
    path('manage-cart-items/<int:pk>/', ManageCartProductView.as_view()),
    path('empty-cart/', EmptyCartView.as_view()),
    path('checkout/', CheckOutView.as_view()),
    path("profile/", CustomerProfileView.as_view(), name="profile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),


    # admin side
    path("admin/orders/", AdminOrderListView.as_view(), name="adminorderlist"),
    path("admin/orders/<int:pk>/",
         AdminOrderDetailView.as_view(), name="adminorderdetail"),
    path("admin/orders-<int:pk>-change/",
         AdminOrderStatusChange.as_view(), name="adminorderstatuschange"),
    path('admin/products/', ProductListView.as_view()),
    path('admin/products/<int:pk>/', ProductDetailView.as_view()),
    path('admin/products/add/', AdminAddProductView.as_view(), name="addproduct"),
]

ecomproject/ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"
urlpatterns = [
    # customer side
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact-us/', ContactView.as_view(), name="contact"),
    path('all-products/', AllProdutView.as_view(), name="all-products"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("search/", SearchView.as_view(), name="search"),
    path("add-to-cart/<int:pro_id>/", AddToCartView.as_view(), name="add-to-cart"),
    path("my-cart/", MyCartView.as_view(), name="my-cart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="empty-cart"),

    path("checkout/", CheckOutView.as_view(), name="checkout"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/", CustomerRegistrationView.as_view(), name="register"),
    path("logout/", CustomerLogoutView.as_view(), name="logout"),
    path("login/", CustomerLoginView.as_view(), name="login"),
    path("profile/", CustomerProfileView.as_view(),
         name="profile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customer-order-detail"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgotpassword"),

    # admin side
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHome.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name="adminorder"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),
    path("admin-order-<int:pk>-change/",
         AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductadd"),

    # payment
    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
]

ecomproject/ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Ecommerce API",
        default_version='v1',
        description="Speed your ecommerce",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
    path('api/', include([
        path('', include('api.urls')),
        path('', schema_view.with_ui('swagger', cache_timeout=0),
             name='schema-swagger-ui'),
    ])),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomproject/ecomapp/models.py
from email.policy import default
from random import choices
from django.contrib.auth.models import User
from django.db import models
from django.utils import tree


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products", null=True, blank=True)
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Cart: ' + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name="cartproducts")
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="cartproducts")
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return 'Cart: ' + str(self.cart.id) + 'CartProduct: ' + str(self.id)


# tuple of the tuple
ORDER_STATUS = (
    ('Order Received', 'Order Received'),
    ('Order Processing', 'Order Processing'),
    ('On the way', 'On the way'),
    ('Order Completed', 'Order Completed'),
    ('Order Cancelled', 'Order Cancelled'),
)


METHOD = (
    ('Cash On Delivery', 'Cash on Delivery'),
    ('Khalti', 'Khalti'),
    ('Esewa', 'Esewa'),
)


class Order(models.Model):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    # payment method
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash on Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return 'Order: ' + str(self.id)

ecomproject/templates/adminpages/admin_order_list.html
{% extends 'adminpages/adminbase.html' %}
{% block title %}All Orders{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All Orders</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Order ID</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in all_orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{ord.id}}</td>
                        <td>{{ord.ordered_by}}</td>
                        <td><a href="{% url 'ecomapp:adminorder' ord.id %}">#ORDER_{{ord.id}}</a></td>
                        <td>{{ord.created_at}}</td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>




{% endblock %}

ecomproject/templates/adminpages/adminbase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
    <div class="container">
        <a href="{% url 'ecomapp:adminhome' %}">Home</a> |
        <a href="{% url 'ecomapp:adminorderlist' %}">All orders</a> |
        <a href="{% url 'ecomapp:adminproductlist' %}">All Products</a> |
        <a href="{% url 'ecomapp:home' %}" target="_blank">Visit Site</a> |
    </div>
    {% block content %}

    {% endblock %}
</body>

</html>

ecomproject/templates/adminpages/adminhome.html
{% extends 'adminpages/adminbase.html' %}
{% block title %}Admin Home{% endblock %}

{% block content %}
<h1 class="text-center">Welcome Mr. {{request.user.username}}</h1>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Pending Orders</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Customer</th>
                        <th>Order ID</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{ord.ordered_by}}</td>
                        <td><a href="{% url 'ecomapp:adminorder' ord.id %}">#ORDER_{{ord.id}}</a></td>
                        <td>{{ord.created_at}}</td>
                        <td>{{ord.total}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>




{% endblock %}

ecomproject/templates/adminpages/adminlogin.html
{% extends 'adminpages/adminbase.html' %}

{% block title %} Admin Login {% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
        text-decoration-style: none;
        list-style-type: none;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login Form</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-primary" type="submit">Login as Admin</button>
                    {% if error %}
                    <li style="color:red">{{error}}</li>
                    {% endif %}
                
                </form>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/adminpages/adminorderdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %}Order Detail {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3>
            <hr>
            <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Ordered On: </span> {{ord_obj.created_at}}
                {{ord_obj.created_at|timesince}} ago</p>
            <p><span class="font-weight-bold">Customer Information: </span>By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}
            </p>
            <p><span class="font-weight-bold">Shipping Information: </span> {{ord_obj.shipping_address}}
                {{ord_obj.email}} </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>

                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank"
                                href="{% url 'ecomapp:product-detail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a>
                        </td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quanity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                        <th>Rs. {{ord_obj.total|intcomma}}/-</th>
                    </tr>
                </tbody>
            </table>
            <form action="{% url 'ecomapp:adminorderstatuschange' ord_obj.id %}" method="POST">
            {% csrf_token %}
            Helllow
            <select name="status" id="">
                {% for i,j in allstatus %}
                <option value="{{i}}" {% if i == ord_obj.order_status %} selected {% endif %} >{{j}}</option>
                {% endfor %}
            </select>
            <button class="btn btn-info">Change</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/adminpages/adminproductadd.html
{% extends 'adminpages/adminbase.html' %} {% block title %} Add new product
{%endblock %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h3>Add New Product</h3>
      <hr />
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form }}
        <button type="submit" class="btn btn-primary">Submit Data</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

ecomproject/templates/adminpages/adminproductlist.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %}All Products {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All product list</h3>
           <a href="{% url 'ecomapp:adminproductadd' %}">Add new product</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product Title</th>
                        <th>Image</th>
                        <th>Price</th>
                        <th>Views</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in allproducts %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{p.title}}</td>
                        <td><img src="{{p.image.url}}" alt="" style="width: 60px" /></td>
                        <td>{{p.selling_price}}</td>
                        <td>{{p.view_count}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>
</div>
{% endblock %}